# Generated by Django 5.2.11 on 2026-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(db_column='Property_Id', db_index=True)),
                ('admin_user_id', models.IntegerField(db_column='Admin_User_Id', db_index=True)),
                ('decision', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
            ],
            options={
                'db_table': 'Property_Reviews',
            },
        ),
    ]
