services:
  traefik:
    image: traefik:v2.11
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - "./infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    depends_on:
      - consul

  consul:
    image: consul:1.15
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "8500:8500"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 0a3aee41df08352ed85b07b5fe48d7f19cfc7a08
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.51.2
    volumes:
      - "./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.1
    ports:
      - "3000:3000"
    volumes:
      - "./infra/grafana/provisioning:/etc/grafana/provisioning:ro"
      - "./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro"
    depends_on:
      - prometheus
<<<<<<< HEAD
=======
=======
>>>>>>> 07acdb2b48ee3790e99efe1efa7a7a09024b125e
>>>>>>> 0a3aee41df08352ed85b07b5fe48d7f19cfc7a08

  auth-service:
    build: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
    environment:
      DB_HOST: host.docker.internal
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      USER_REGISTERED_QUEUE: user_registered
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
>>>>>>> 07acdb2b48ee3790e99efe1efa7a7a09024b125e
>>>>>>> 0a3aee41df08352ed85b07b5fe48d7f19cfc7a08
      CONSUL_HTTP_ADDR: http://consul:8500
      SERVICE_NAME: auth-service
      SERVICE_HOST: auth-service
      SERVICE_PORT: "8000"
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq

  account-service:
    build: ./services/account-service
    env_file:
      - ./services/account-service/.env
    environment:
      DB_HOST: host.docker.internal
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
>>>>>>> 07acdb2b48ee3790e99efe1efa7a7a09024b125e
>>>>>>> 0a3aee41df08352ed85b07b5fe48d7f19cfc7a08
      CONSUL_HTTP_ADDR: http://consul:8500
      SERVICE_NAME: account-service
      SERVICE_HOST: account-service
      SERVICE_PORT: "8000"
    ports:
      - "8002:8000"

  location-service:
    build: ./services/location-service
    env_file:
      - ./services/location-service/.env
    environment:
      DB_HOST: host.docker.internal
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
>>>>>>> 07acdb2b48ee3790e99efe1efa7a7a09024b125e
>>>>>>> 0a3aee41df08352ed85b07b5fe48d7f19cfc7a08
      CONSUL_HTTP_ADDR: http://consul:8500
      SERVICE_NAME: location-service
      SERVICE_HOST: location-service
      SERVICE_PORT: "8000"
    ports:
      - "8003:8000"

  listing-service:
    build: ./services/listing-service
    env_file:
      - ./services/listing-service/.env
    environment:
      DB_HOST: host.docker.internal
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
>>>>>>> 07acdb2b48ee3790e99efe1efa7a7a09024b125e
>>>>>>> 0a3aee41df08352ed85b07b5fe48d7f19cfc7a08
      CONSUL_HTTP_ADDR: http://consul:8500
      SERVICE_NAME: listing-service
      SERVICE_HOST: listing-service
      SERVICE_PORT: "8000"
    ports:
      - "8004:8000"

  admin-validation-service:
    build: ./services/admin-validation-service
    env_file:
      - ./services/admin-validation-service/.env
    environment:
      DB_HOST: host.docker.internal
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
<<<<<<< HEAD
      REDIS_URL: redis://redis:6379/0
=======
>>>>>>> 07acdb2b48ee3790e99efe1efa7a7a09024b125e
>>>>>>> 0a3aee41df08352ed85b07b5fe48d7f19cfc7a08
      CONSUL_HTTP_ADDR: http://consul:8500
      SERVICE_NAME: admin-validation-service
      SERVICE_HOST: admin-validation-service
      SERVICE_PORT: "8000"
    ports:
      - "8005:8000"

  notification-worker:
    build: ./services/notification-worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      USER_REGISTERED_QUEUE: user_registered
    depends_on:
      - rabbitmq

  ui-web:
    build: ./ui/web
    environment:
      VITE_AUTH_BASE_URL: http://localhost:8080/api/auth
      VITE_ACCOUNT_BASE_URL: http://localhost:8080/api/account
      VITE_LOCATION_BASE_URL: http://localhost:8080/api/location
      VITE_LISTING_BASE_URL: http://localhost:8080/api/listing
    ports:
      - "5173:5173"
    depends_on:
      - traefik

  ui-admin:
    build: ./ui/admin
    environment:
      VITE_AUTH_BASE_URL: http://localhost:8080/api/auth
      VITE_ACCOUNT_BASE_URL: http://localhost:8080/api/account
      VITE_LOCATION_BASE_URL: http://localhost:8080/api/location
      VITE_LISTING_BASE_URL: http://localhost:8080/api/listing
    ports:
      - "5174:5174"
    depends_on:
      - traefik

volumes: {}
