# Generated by Django 5.2.11 on 2026-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='User_Id', db_index=True)),
                ('company_name', models.CharField(db_column='Company_Name', max_length=510)),
                ('owner_name', models.CharField(db_column='OwnerName', max_length=510)),
                ('commune_id', models.IntegerField(db_column='Commune_Id', db_index=True)),
                ('registration_number', models.CharField(db_column='RegistrationNumber', max_length=510)),
                ('logo_url', models.CharField(blank=True, db_column='LogoUrl', max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Agences',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='User_Id', db_index=True)),
                ('full_name', models.CharField(max_length=510)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('avatar_url', models.CharField(blank=True, db_column='AvatarUrl', max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At', null=True)),
            ],
            options={
                'db_table': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='User_Id', db_index=True)),
                ('company_name', models.CharField(db_column='Company_Name', max_length=510)),
                ('owner_name', models.CharField(db_column='OwnerName', max_length=510)),
                ('registration_number', models.CharField(db_column='RegistrationNumber', max_length=510)),
                ('commune_id', models.IntegerField(db_column='Commune_Id', db_index=True)),
                ('logo_url', models.CharField(blank=True, db_column='LogoUrl', max_length=510, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Promoteurs',
            },
        ),
    ]
