# Generated by Django 5.2.11 on 2026-03-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510)),
                ('email', models.EmailField(max_length=510, unique=True)),
                ('password_hash', models.CharField(max_length=510)),
                ('phone', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('role', models.ForeignKey(db_column='Role_Id', on_delete=django.db.models.deletion.PROTECT, to='auth_service.role')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField(db_column='Expires_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At')),
                ('revoked_at', models.DateTimeField(blank=True, db_column='Revoked_At', null=True)),
                ('user', models.ForeignKey(db_column='User_Id', on_delete=django.db.models.deletion.CASCADE, to='auth_service.user')),
            ],
            options={
                'db_table': 'RefreshTokens',
            },
        ),
    ]
