# Generated by Django 5.2.12 on 2026-03-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('postcode', models.CharField(max_length=20)),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ber', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Wilayas',
            },
        ),
        migrations.CreateModel(
            name='Daira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('wilaya', models.ForeignKey(db_column='Wilaya_Id', on_delete=django.db.models.deletion.PROTECT, to='location_service.wilaya')),
            ],
            options={
                'db_table': 'Dairas',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('daira', models.ForeignKey(blank=True, db_column='Daira_Id', null=True, on_delete=django.db.models.deletion.PROTECT, to='location_service.daira')),
                ('wilaya', models.ForeignKey(db_column='Wilaya_Id', on_delete=django.db.models.deletion.PROTECT, to='location_service.wilaya')),
            ],
            options={
                'db_table': 'Communes',
            },
        ),
    ]
