from django.urls import path

from listing_service.views import (
    CategoryListView,
    CategoryDetailView,
    StatusPropertyListView,
    TypeListView,
    TypeDetailView,
    AmenityListView,
    AmenityDetailView,
    DocumentTypeListView,
    DocumentTypeDetailView,
    ContactTypeListView,
    PropertyCreateView,
    PropertyListView,
    PropertyDetailView,
    PropertyImageDeleteView,
    PropertyDocumentListCreateView,
    PropertyDocumentDeleteView,
    PropertyContactListCreateView,
    PropertyContactDeleteView,
    PropertyContactUpdateView,
    PropertyLikeToggleView,
    PropertyLikeCountView,
)


urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
    path("types/", TypeListView.as_view(), name="type-list"),
    path("types/<int:pk>/", TypeDetailView.as_view(), name="type-detail"),
    path("statuses/", StatusPropertyListView.as_view(), name="status-list"),
    path("amenities/", AmenityListView.as_view(), name="amenity-list"),
    path("amenities/<int:pk>/", AmenityDetailView.as_view(), name="amenity-detail"),
    path("document-types/", DocumentTypeListView.as_view(), name="document-type-list"),
    path("document-types/<int:pk>/", DocumentTypeDetailView.as_view(), name="document-type-detail"),
    path("contact-types/", ContactTypeListView.as_view(), name="contact-type-list"),
    path("properties/", PropertyCreateView.as_view(), name="property-create"),
    path("properties/list/", PropertyListView.as_view(), name="property-list"),
    path("properties/<int:pk>/", PropertyDetailView.as_view(), name="property-detail"),
    path("properties/<int:property_id>/images/<int:pk>/", PropertyImageDeleteView.as_view(), name="property-image-delete"),
    path("properties/<int:property_id>/documents/", PropertyDocumentListCreateView.as_view(), name="property-document-list-create"),
    path("properties/<int:property_id>/documents/<int:pk>/", PropertyDocumentDeleteView.as_view(), name="property-document-delete"),
    path("properties/<int:property_id>/contacts/", PropertyContactListCreateView.as_view(), name="property-contact-list-create"),
    path("properties/<int:property_id>/contacts/<int:pk>/", PropertyContactDeleteView.as_view(), name="property-contact-delete"),
    path("properties/<int:property_id>/contacts/<int:pk>/update/", PropertyContactUpdateView.as_view(), name="property-contact-update"),
    path("properties/<int:property_id>/like/", PropertyLikeToggleView.as_view(), name="property-like-toggle"),
    path("properties/<int:property_id>/likes/", PropertyLikeCountView.as_view(), name="property-like-count"),
]
