# Generated by Django 5.2.11 on 2026-03-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510, unique=True)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='StatusProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Status_Properties',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=510, unique=True)),
            ],
            options={
                'db_table': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='User_Id', db_index=True)),
                ('commune_id', models.IntegerField(db_column='Commune_Id', db_index=True)),
                ('title', models.CharField(max_length=510)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('area', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Created_At', null=True)),
                ('category', models.ForeignKey(db_column='Category_Id', on_delete=django.db.models.deletion.PROTECT, to='listing_service.category')),
                ('status', models.ForeignKey(db_column='Status_Id', on_delete=django.db.models.deletion.PROTECT, to='listing_service.statusproperty')),
                ('type', models.ForeignKey(db_column='Type_Id', on_delete=django.db.models.deletion.PROTECT, to='listing_service.type')),
            ],
            options={
                'db_table': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(db_column='Image_Url', max_length=510)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(db_column='Property_Id', on_delete=django.db.models.deletion.CASCADE, to='listing_service.property')),
            ],
            options={
                'db_table': 'Property_Images',
            },
        ),
    ]
