# Generated by Django 5.2.12 on 2026-03-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_file',
            field=models.ImageField(blank=True, db_column='Image_File', null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.CharField(blank=True, db_column='Image_Url', max_length=510, null=True),
        ),
    ]
